import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SideBarLeft from "./components/sideBarLeft";
import Header from "./components/header";
import ThemeToggle from "./components/themeToggle";
import Provider from "./provider/themeProvider";
import ViewRecipe from "./components/viewRecipe";
import SettingsButton from "./components/settingsButton";
import RightPanel from "./components/RightPanel";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  name: "viewport",
  content: "width=device-width, initial-scale=1.0",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en" >
        <body className="wrapper">
          <Provider>    
            <ThemeToggle />
            <div className="bottom-right-controls">
              <SettingsButton />    
            </div>        
          </Provider>
          <header>
            < Header />
          </header>
          <br></br>       
          <aside className="left"> 
            < SideBarLeft />
          </aside>
          <main className="middle">
            {children}
          </main> 
          <aside className="right">
            <RightPanel />
          </aside>
      </body>
    </html>
  );
}
