import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SideBarLeft from "./components/sideBarLeft";
import Header from "./components/header";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  name: "viewport",
  content: "width=device-width, initial-scale=1.0",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable}`}>
          <header>
            < Header />
          </header>

          <aside> 
            < SideBarLeft />
          </aside>

          <main>
            {children}
          </main> 
      </body>
    </html>
  );
}
